# Generated by Django 6.0.3 on 2026-04-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_product_category_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(upload_to='media/category_image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='media/product'),
        ),
    ]
