# Generated by Django 6.0.3 on 2026-04-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='varified_email',
            field=models.BooleanField(default=True),
        ),
    ]
