# Generated by Django 6.0.3 on 2026-04-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_profile_varified_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='varified_email',
            field=models.BooleanField(default=False),
        ),
    ]
